spring.application.name=EcoCheck2026
server.servlet.context-path=/ecocheck

#Database configs
spring.datasource.url=jdbc:mysql://localhost:3306/ecoCheckCMJD2026?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Isara1405
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA configs/ Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
